drying a bit, broke test
AloeareV/zingolib pull request #23
Opened 2023-03-14 19:50 UTC by zancas

I broke a test.

2023-03-15 03:47 UTC, zancas commented
Would it makes sense to defined new type:
`struct MemoBytes([u8; 511])`
?

It's first byte must always be a valid version number.
I think for v0 memo's we know some bytes at the end have to be `0u8`.

2023-03-16 17:47 UTC, AloeareV requested changes
Looks great, much DRYer! One small change

2023-03-16 17:47 UTC, AloeareV commented on zingo-memo/src/memo_serde.rs
> +        x @ _ => {
This can just be
```suggestion
        x => {
```

2023-03-16 18:21 UTC, zancas reviewed
OK, I made your suggested change!

2023-03-16 19:22 UTC, AloeareV approved these changes

2023-03-16 19:22 UTC, merged